"""vehicle, order

Revision ID: 97621567831b
Revises: ea6d1e2c0235
Create Date: 2026-01-12 10:06:51.143771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97621567831b'
down_revision = 'ea6d1e2c0235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_cleaning_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('requested_service_date', sa.Date(), nullable=False),
    sa.Column('requested_service_time_slot', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_cleaning_vehicle_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['house_cleaning_orders.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['house_cleaning_partner_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_cleaning_auto_matching_time_management',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('time_slot_availability', sa.Integer(), nullable=False),
    sa.Column('vehicle_address_geolocation', sa.String(length=255), nullable=False),
    sa.Column('vehicle_work_schedule_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_assignment_id', sa.Integer(), nullable=True),
    sa.Column('workplace_geolocation', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_assignment_id'], ['house_cleaning_vehicle_assignments.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['house_cleaning_partner_vehicles.id'], ),
    sa.ForeignKeyConstraint(['vehicle_work_schedule_id'], ['house_cleaning_vehicle_work_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('house_cleaning_auto_matching_time_management')
    op.drop_table('house_cleaning_vehicle_assignments')
    op.drop_table('house_cleaning_orders')
    op.drop_table('customers')
    # ### end Alembic commands ###
