"""Initialize all tables

Revision ID: ea6d1e2c0235
Revises: 
Create Date: 2026-01-08 17:03:12.301815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6d1e2c0235'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house_cleaning_partner_staffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_kana', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_cleaning_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_cleaning_partner_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['house_cleaning_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_cleaning_vehicle_work_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('work_start_at', sa.Time(), nullable=False),
    sa.Column('work_end_at', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['house_cleaning_partner_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_cleaning_vehicle_occupants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_schedule_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['house_cleaning_partner_staffs.id'], ),
    sa.ForeignKeyConstraint(['work_schedule_id'], ['house_cleaning_vehicle_work_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('house_cleaning_vehicle_occupants')
    op.drop_table('house_cleaning_vehicle_work_schedules')
    op.drop_table('house_cleaning_partner_vehicles')
    op.drop_table('house_cleaning_partners')
    op.drop_table('house_cleaning_partner_staffs')
    # ### end Alembic commands ###
